### ISSUE TITLE
https://github.com/square/wire/pull/1994 fixes this for me locally.

### ISSUE THREAD

**Issue by viviskas** [square/wire#1996] opened 2021-06-20 17:02 UTC
https://github.com/square/wire/pull/1994 fixes this for me locally.

_Originally posted by @staktrace in https://github.com/square/wire/issues/1859#issuecomment-863527909_

**Comment by oldergod** [comment] 2021-06-21 14:01
Not sure what the issue is so I'm closing it.

**Closed by oldergod** 2021-06-21 14:01 UTC
