### ISSUE TITLE
Task with name 'compileJava' not found in project

### ISSUE THREAD

**Issue by felipethalmic** [square/wire#1241] opened 2019-10-23 15:16 UTC
I'm trying to use Wire plugin on Android Studio, but I'm getting this error
`Task with name 'compileJava' not found in project`

This is the configuration I have so far
```
dependencies {
    classpath "com.squareup.wire:wire-gradle-plugin:3.0.1"
}
```
`apply plugin: 'com.squareup.wire'`

**Comment by JakeWharton** [comment] 2019-10-23 18:10
Dupe of #881. Use a Java or Kotlin module for now.

**Closed by JakeWharton** 2019-10-23 18:10 UTC
