### ISSUE TITLE
Optional Type does not support in grpc client.

### ISSUE THREAD

**Issue by czf0613** [square/wire#2326] opened 2022-08-14 15:39 UTC
Hello, I got a problem when using the wire protobuf and grpc client.

The grpc service is as follows:
rpc GetCurrentCoinCount (google.protobuf.Empty) returns (google.protobuf.UInt32Value);

I used the wrapper value of 'uint32', and it should be represented as 'UInt?' in Kotlin.
But it has a error show that "Type argument is not within its bounds: should be subtype of 'Any'", 
and the generated kotlin grpc service client code is as follows:
public fun GetCurrentCoinCount(): GrpcCall<Unit, Int?>

But, the prototype of GrpcCall is "public interface GrpcCall<S : Any, R : Any>", so that piece of code causes compilation error.
Is there any solution? Thanks sincerely.

**Comment by oldergod** [comment] 2022-08-15 13:08
Thanks for reporting. This is a duplicate of #1912

**Closed by oldergod** 2022-08-15 13:08 UTC
