### ISSUE TITLE
The plugin does not add the generated sources to Android SourceSet

### ISSUE THREAD

**Issue by danielgomezrico** [square/wire#1549] opened 2020-05-15 00:35 UTC
Hi

Im using the plugin on an android app and I can see the generated classes over `app/build/generated/wired/mypackage/MyClass.kt` but I am not been able to import the class from my app code.

One solution I found was manually adding to the source set the generated code

```
android{
    sourceSets {
        main.java.srcDirs += "${buildDir}/generated/source/wire/"
```

But it feels like a step that I should not do manually since retrofit works without this kind of things.

Maybe there's something missing in my setup to make it work?

# Dependencies
```
- plugin classpath 'com.squareup.wire:wire-gradle-plugin:3.2.1'
- dependency: "com.squareup.wire:wire-runtime:3.2.1"
```

# Setup

```
apply plugin: 'com.squareup.wire'

android { ... }

wire {
    kotlin {
        includes = ['com.lahaus.sales.*']
        exclusive = false
        android = true
        javaInterop = false

        protoPath {
            srcDir 'src/main/proto'
        }
    }
}
```

**Comment by danielgomezrico** [comment] 2020-05-15 00:36
Seems like it's duplicated from https://github.com/square/wire/issues/1123

**Comment by oldergod** [comment] 2020-05-15 01:18
Duplicate of #1123 indeed, we'll follow up over there.

**Closed by oldergod** 2020-05-15 01:18 UTC
